name: Run node

on:
  workflow_dispatch:
  
  
jobs:
  RunNode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Test
        run: |
          cd react-test-componentdidupdate
          npm install
